### **IMPORTANDO LIBRERÍAS**

In [ ]:
import numpy as np # el np es un alias del nombre de la biblioteca numpy
import sys # este paquete maneja funciones del sistema, al ser corto no es necesario darle un alias

### **Creando una lista de 10 elementos**

In [ ]:
lista1 = list(range(1, 11))
lista1

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

### **Transformado la lista a un Array**

recordar que un `array` es una estructura propia de la librería numpy.

In [ ]:
arreglo = np.array(lista1)
arreglo

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

### **Consultando el tipo de dato númerico del arreglo**

In [ ]:
arreglo.dtype

dtype('int64')

### **Crear una lista de solo números uno y cero**



In [ ]:
unos = np.ones(100)
unos

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
ceros = np.zeros(100)
ceros

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

### **Lista de Datos Compuestos (Transformando a Array)**

In [ ]:
lista2 = ['Victor', 2, 5.6, True]
lista2

['Victor', 2, 5.6, True]

### **Transformando la lista en Array**

In [ ]:
arreglo2 = np.array(lista2)
arreglo2

### **Consultando la cantidad de memoria ocupada por estructura (Paquete Sys)**

In [ ]:
memoria_lista = sys.getsizeof(lista1)
memoria_arreglo = arreglo.nbytes

print(f"Memoria ocupada por la lista: {memoria_lista} bytes")
print(f"Memoria ocupada por el array: {memoria_arreglo} bytes")

Memoria ocupada por la lista: 136 bytes
Memoria ocupada por el array: 80 bytes


### **Otros métodos de Numpy**

In [ ]:
print("Shape:", arreglo.shape)         # Dimensiones
print("Dimensiones:", arreglo.ndim)    # Número de ejes
print("Tamaño:", arreglo.size)         # Tipo de Tamaño
print("Tipo de Dato:", arreglo.dtype)  # Tamaño de almacenamiento
print("Bytes/elem:", arreglo.itemsize) # Tamaño en bytes de cada elemento

Shape: (10,)
Dimensiones: 1
Tamaño: 10
Tipo de Dato: int64
Bytes/elem: 8


### **Obteniendo el Promedio del Arreglo**

In [ ]:
promedio = np.mean(lista1)
promedio

np.float64(5.5)

### **Transformando el Arreglo de Int a Float**

El método astype() transforma los elementos

In [ ]:
new_arreglo = arreglo.astype(np.float16) # Se puede especificar el tipo de n° flotante (float16, float32, float64, etc.)
new_arreglo

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.], dtype=float16)

### **Aplicando el Paquete Random**

Se genera una lista de números enteros aleatorios, que van del 1 al 100

In [ ]:
np.random.rand() # genera números aleatorios del rango [0,1]

0.5306914678073946

In [ ]:
np.random.rand(5) # genera números aleatorios del rango [0,1], pero en este caso n cantidad

array([0.56150169, 0.54513827, 0.52546234, 0.28076405, 0.85647278])

In [ ]:
np.random.randint(10) # genera números enteros aleatorios del rango [1,10]

1

In [ ]:
np.random.rand(1, 10, 4) # genera números aleatorios del rango [0,1], en este caso como una matriz de números, generando columnas

array([[[0.18432207, 0.33784415, 0.60991116, 0.99047957],
        [0.82423394, 0.49250661, 0.29031057, 0.19509044],
        [0.96047467, 0.31236305, 0.83573781, 0.45775507],
        [0.66726263, 0.51647074, 0.69139205, 0.64836874],
        [0.86668944, 0.70949904, 0.13876703, 0.89536441],
        [0.85406373, 0.3232825 , 0.1993934 , 0.09410649],
        [0.46296351, 0.92560886, 0.34677012, 0.67013905],
        [0.35300309, 0.26250487, 0.8520195 , 0.80730394],
        [0.20682652, 0.17988565, 0.77046171, 0.60304084],
        [0.64261844, 0.96744052, 0.18318652, 0.28124172]]])

In [ ]:
np.random.randint(1, 100, 10) # generando 10 números aleatorios del 1 al 100
                              # El 1 representa el rango minimo y el 100 el rango maximo, mientras que el 10 es la cantidad de veces que genera los estos números

array([ 3, 46, 48, 59, 25, 57, 44, 35, 73, 64])

### **Método Arange**

In [ ]:
arreglo3 = np.arange(1,11)
arreglo3

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
arreglo_aleatorio2 = np.random.randint()